#Basso Nicola
#4^AI
#sono disponibili: all, compile, clean

CC=gcc
RM=rm -f

SRC=dyn_array.c
EXC=dyn_array

all: compile run

compile:
	$(CC) -o $(EXC) $(SRC)

clean:
	reset
	$(RM) $(EXC)

run:
	./$(EXC)
