#Basso Nicola
#4^AI

SRC=graduatoria.c
SRC2=pila.c

EXC=graduatoria
EXC2=pila

all: compile compile2

compile:
	@gcc -o $(EXC) $(SRC) -Wall

compile2:
	@gcc -o $(EXC2) $(SRC2) -Wall

run:
	@./$(EXC)

run2:
	@./$(EXC2)
