#Basso Nicola
#4^AI
#modificare EXC in Basso1 o Basso2 per eseguire i vari programmi

CC = gcc
RM = rm -f

EXC = Basso2

all: clean compile run

compile:
	@$(CC) -o $(EXC) $(EXC).c

clean:
	@$(RM) $(EXC)

run:
	@./$(EXC)
