#Basso Nicola
#4^AI
#sono disponibili: all, compile, clean

CC=gcc
RM=rm -f

SRC=Basso_liste.c
EXC=Basso_liste

all: compile run

compile:
	$(CC) -o $(EXC) $(SRC)

clean:
	reset
	$(RM) $(EXC)

run:
	./$(EXC)
